import type { IntentLexicon } from './types';

export const EN: IntentLexicon = {
  count: ['how many', 'times'],
  earnedIncome: [],
  incomeWord: ['income', 'payroll'],
  savings: ['savings', 'saved', 'save'],
  savingsStems: [],
  projection: [
    'will i spend',
    'going to spend',
    'will i save',
    'can i save',
    'going to save',
    'left to spend',
    'end of the month',
    'end of month',
    'forecast',
    'projection',
    'projected',
    'at this pace',
  ],
  cut: ['cut back', 'cut down', 'spend less', 'where can i save', 'trim'],
  afford: ['can i afford', 'afford', 'can i buy', 'can i spend'],
  ant: ['small spend', 'small spends', 'ant spend', 'ant expense', 'ant expenses'],
  spendVerb: ['spend', 'spent', 'expense', 'expenses'],
  payVerb: ['paid', 'pay', 'payment', 'payments'],
  debt: ['debt', 'loan'],
  debtPayment: ['debt payment', 'installment', 'installments', 'obligations', 'obligation'],
  available: ['available'],
  compare: ['more than', 'less than'],
  origin: ['which account', 'which pocket', 'from which'],
  transfer: ['transfer'],
  top: ['biggest', 'most spent', 'where did i spend'],
  average: ['average'],
  budget: ['budget'],
  percent: ['percent', 'share of'],
  leftNow: ['have left', 'money left'],
  monthEnd: ['end of', 'at this pace'],
  totals: ['spend', 'spent', 'expense', 'expenses'],
};
