import type { IntentLexicon } from './types';

export const ES: IntentLexicon = {
  count: ['cuantas', 'cuántas', 'cuantos', 'cuántos', 'veces', 'conteo'],
  earnedIncome: ['gane', 'gané', 'recibi', 'recibí', 'cobre', 'cobré'],
  incomeWord: ['ingreso', 'ingresos', 'salario', 'sueldo', 'nomina', 'nómina'],
  savings: ['sobro', 'sobró', 'balance', 'neto del mes'],
  savingsStems: ['ahorr'],
  projection: [
    'voy a gastar',
    'vamos a gastar',
    'gastare',
    'voy a ahorrar',
    'puedo ahorrar',
    'podre ahorrar',
    'me queda',
    'me quedara',
    'nos queda',
    'fin de mes',
    'final del mes',
    'cierre del mes',
    'cerrar el mes',
    'cerraria',
    'proyeccion',
    'a este ritmo',
  ],
  cut: [
    'recortar',
    'recorto',
    'recorte',
    'reducir',
    'gastar menos',
    'ahorrar en',
    'donde ahorro',
    'en que ahorro',
  ],
  afford: ['puedo comprar', 'me alcanza', 'alcanza para', 'puedo gastar', 'puedo pagar'],
  ant: ['hormiga', 'hormigas', 'gasto hormiga', 'gastos hormiga'],
  spendVerb: ['gaste', 'gasté', 'gasto', 'gastos'],
  payVerb: ['pague', 'pagué', 'pago', 'pagos', 'abono', 'abonos'],
  debt: [
    'deuda',
    'deudas',
    'credito activo',
    'crédito activo',
    'saldo de deuda',
    'cuanto debo',
    'cuánto debo',
  ],
  debtPayment: [
    'cuota',
    'cuotas',
    'pago de deuda',
    'pagos de deuda',
    'pague deuda',
    'pagué deuda',
    'pague una deuda',
    'pagué una deuda',
    'pague a credito',
    'pagué a crédito',
    'pague a creditos',
    'pagué a créditos',
    'pague creditos',
    'pagué créditos',
    'pagos a creditos',
    'pagos a créditos',
    'obligacion',
    'obligación',
    'obligaciones',
  ],
  available: ['disponible', 'liquidez', 'cuanto tengo', 'cuánto tengo', 'tengo en cuentas'],
  compare: [
    'mas que',
    'más que',
    'menos que',
    'compar',
    'aumento',
    'vs',
    'versus',
    'respecto',
    'contra el mes',
    'contra la semana',
  ],
  origin: [
    'de que cuenta',
    'de qué cuenta',
    'de que bolsillo',
    'de qué bolsillo',
    'de donde salio',
    'de dónde salió',
    'de donde sale',
  ],
  transfer: ['transferencia', 'transferencias', 'envie', 'envié'],
  top: [
    'mas gaste',
    'más gasté',
    'mas gasto',
    'más gasto',
    'en que gaste',
    'en qué gasté',
    'en que gaste mas',
    'en qué gasté más',
    'mayor gasto',
    'top',
    'categoria mas alta',
    'categoría más alta',
  ],
  average: ['promedio', 'media', 'por movimiento', 'por gasto'],
  budget: ['tope', 'topes', 'presupuesto', 'limite', 'límite', 'sobre el tope'],
  percent: [
    'porcentaje',
    'por ciento',
    'proporcion',
    'proporción',
    '%',
    'cuota del',
    'parte del',
  ],
  leftNow: ['me queda', 'nos queda', 'tengo disponible'],
  monthEnd: ['fin de mes', 'final del mes', 'cierre', 'a este ritmo', 'quedara'],
  totals: ['gaste', 'gasté', 'gasto', 'gastos', 'cuanto', 'cuánto', 'total'],
};
