import { StyleSheet } from 'react-native';

import { colors, radius, space, type } from '@/src/theme';
import { palette, radii } from '@/src/theme/colors';

/** Styles shared by the Wealth screen and its sections. */
export const styles = StyleSheet.create({
  addKinds: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: space.xs,
    marginTop: space.xs,
  },
  addKind: {
    borderWidth: 1,
    borderColor: colors.border.strong,
    borderStyle: 'dashed',
    borderRadius: radius.full,
    paddingHorizontal: space.md,
    paddingVertical: space.xs,
    backgroundColor: colors.bg.surface,
  },
  addKindOn: {
    borderStyle: 'solid',
    borderColor: colors.action.secondary,
    backgroundColor: 'rgba(27,58,75,0.08)',
  },
  addKindText: {
    fontFamily: type.label.fontFamily,
    fontSize: 14,
    color: colors.action.secondary,
  },
  addKindTextOn: {
    color: colors.text.primary,
  },
  addPanel: {
    marginTop: space.sm,
    backgroundColor: colors.bg.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    padding: space.md,
  },
  groupCard: {
    backgroundColor: colors.bg.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    overflow: 'hidden',
  },
  accRow: {
    paddingHorizontal: space.md,
    paddingVertical: space.sm,
  },
  accRowDivider: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border.strong,
  },
  accMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.sm,
    minHeight: 40,
  },
  accBadge: {
    width: 32,
    height: 32,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accBadgeText: {
    fontFamily: type.title.fontFamily,
    fontSize: 15,
  },
  accText: { flex: 1, gap: 2 },
  accTitle: {
    fontFamily: type.title.fontFamily,
    fontSize: 16,
  },
  accBalance: {
    ...type.amount,
    color: colors.text.primary,
    maxWidth: '45%',
    textAlign: 'right',
  },
  accActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: space.lg,
    marginTop: space.sm,
    marginLeft: 32 + space.sm,
  },
  accountsHint: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    color: colors.text.secondary,
    lineHeight: 18,
    marginBottom: 10,
  },
  groupLabel: {
    fontFamily: 'DMSans_700Bold',
    fontSize: 12,
    color: colors.text.tertiary,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginTop: 8,
    marginBottom: 6,
  },
  groupLabelFirst: {
    marginTop: 0,
  },
  net: {
    gap: space.xxs,
  },
  netValue: {
    ...type.display,
    color: colors.text.onBrand,
  },
  netSplit: {
    marginTop: space.xxs,
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: space.md,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  copyHint: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    color: palette.inkMuted,
    lineHeight: 18,
    marginBottom: 8,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 4,
  },
  chip: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radii.sm,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#fff',
  },
  chipOn: {
    borderColor: palette.accent,
    backgroundColor: palette.accentSoft,
  },
  chipText: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 13,
    color: palette.inkMuted,
  },
  chipTextOn: {
    color: palette.ink,
  },
  formTitle: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 15,
    color: palette.ink,
    marginBottom: 6,
  },
  addBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.sm,
    backgroundColor: palette.teal,
  },
  addBtnText: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 13,
    color: palette.white,
  },
  debtActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  payBtn: {
    flex: 1,
    backgroundColor: palette.accent,
    borderRadius: radii.md,
    paddingVertical: 12,
    alignItems: 'center',
  },
  chargeBtn: {
    backgroundColor: palette.teal,
  },
  payBtnText: {
    fontFamily: 'DMSans_700Bold',
    fontSize: 15,
    color: palette.white,
  },
  chargeHint: {
    marginTop: 8,
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    color: palette.inkMuted,
    lineHeight: 18,
  },
  summaryCard: {
    backgroundColor: palette.surfaceSolid,
    borderRadius: radii.md,
    padding: 14,
    borderWidth: 1,
    borderColor: palette.border,
    marginBottom: 10,
  },
  summaryTitle: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 14,
    color: palette.ink,
  },
  form: {
    backgroundColor: palette.surfaceSolid,
    borderRadius: radii.md,
    padding: 14,
    borderWidth: 1,
    borderColor: palette.border,
    marginBottom: 10,
    gap: 6,
  },
  formActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  label: {
    marginTop: 6,
    fontFamily: 'DMSans_500Medium',
    fontSize: 13,
    color: palette.inkMuted,
  },
  input: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radii.sm,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    color: palette.ink,
    backgroundColor: '#fff',
  },
  saveBtn: {
    marginTop: 4,
    backgroundColor: palette.teal,
    borderRadius: radii.sm,
    paddingVertical: 12,
    alignItems: 'center',
    flex: 1,
  },
  saveBtnFlex: { flex: 1 },
  saveBtnText: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 15,
    color: palette.white,
  },
  secondaryBtn: {
    marginTop: 4,
    flex: 1,
    borderRadius: radii.sm,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: '#fff',
  },
  secondaryBtnText: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 14,
    color: palette.inkMuted,
  },
  card: {
    backgroundColor: palette.surfaceSolid,
    borderRadius: radii.md,
    padding: 14,
    borderWidth: 1,
    borderColor: palette.border,
    marginBottom: 10,
  },
  walletRename: {
    marginTop: 10,
    gap: 6,
  },
  cardEditing: {
    borderColor: palette.teal,
  },
  cardActions: {
    alignItems: 'flex-end',
    gap: 8,
  },
  cardTitle: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 16,
    color: palette.ink,
  },
  cardHint: {
    marginTop: 2,
    fontFamily: 'DMSans_400Regular',
    fontSize: 12,
    color: palette.inkMuted,
  },
  conceptChip: {
    marginTop: 2,
    fontFamily: 'DMSans_400Regular',
    fontSize: 12,
    color: palette.inkMuted,
  },
  amount: {
    marginTop: 8,
    fontFamily: 'Fraunces_600SemiBold',
    fontSize: 24,
    color: palette.ink,
  },
  metricRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 8,
  },
  metricLabel: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 14,
    color: palette.inkMuted,
    flexShrink: 1,
  },
  metricValue: {
    fontFamily: 'Fraunces_600SemiBold',
    fontSize: 20,
    color: palette.ink,
  },
  amountDebt: {
    color: palette.danger,
    fontSize: 16,
    fontFamily: 'DMSans_600SemiBold',
  },
  meta: {
    marginTop: 4,
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    color: palette.inkMuted,
  },
  track: {
    marginTop: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#E8EEF1',
    overflow: 'hidden',
  },
  fill: { height: '100%', borderRadius: 999 },
  editText: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 13,
    color: palette.tealText,
  },
  deleteText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 13,
    color: palette.danger,
  },
  link: {
    marginTop: 8,
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 13,
    color: palette.tealText,
  },
  empty: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: palette.inkMuted,
    lineHeight: 20,
  },
  hint: {
    marginTop: 4,
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    color: palette.inkMuted,
    lineHeight: 18,
  },
});
